PFB_Typography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import pages.views, catalog.views, core.views, orders.views, reviews.views, users.views
from django.conf.urls import handler404, handler500

handler400 = 'core.views.custom_400'
handler403 = 'core.views.custom_403'
handler404 = 'core.views.custom_404'
handler500 = 'core.views.custom_500'

urlpatterns = [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', pages.views.main ,name='main'),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('about_us/', pages.views.about_us ,name="about_us"),
    path('pay-delivery/', pages.views.pay_delivery ,name="pay_delivery"),
    path('question–answer/', pages.views.question_answer ,name="question_answer"),
    path('account/', include('users.urls', namespace='user')),
    path('news/', include('news.urls', namespace='news')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('nested_admin/', include('nested_admin.urls')),
    path('activate/<uidb64>/<token>/', core.views.activate_account, name="activate_account"),
    path('email-change/<uidb64>/<token>/', core.views.change_email_confirm, name='change_email_confirm'),
    path("portfolio/", pages.views.portfolio_view, name="portfolio"),
    path("return-policy/", pages.views.return_policy_view, name="return_policy"),
    path("terms-of-use/", pages.views.terms_of_use_view, name="terms_of_use"),
    path("privacy-policy/", pages.views.privacy_policy_view, name="privacy_policy"),
    path('checkout/', orders.views.checkout, name='checkout'),
    path('add-order-recipient/<int:order_id>/', orders.views.add_order_recipient, name='add_order_recipient'),
    path('update-order-recipient/<int:order_id>/', orders.views.update_order_recipient, name='update_order_recipient'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('send-message/', views.send_message, name="send_message"),
    path('upload-chat/', views.upload_chat, name="upload_chat"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import CustomPasswordChangeForm

app_name = 'user'

urlpatterns = [
    path('my-orders/', views.my_orders_view, name='my_orders'),
    path('order-detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('messages/', views.view_messages, name="messages"),
    path('favorites/', views.favorites, name="favorites"),
    path('favorites/remove-selected-favorites/', views.remove_selected_favorites, name="remove_selected_favorites"),
    path('remove-from-favorites/<slug:slug>/', views.remove_from_favorites, name="remove_from_favorites"),
    path('add-to-favorites/<slug:slug>/', views.add_to_favorites, name="add_to_favorites"),
    path('', views.dashboard , name="dashboard"),
    path('logout/', views.CustomLogout.as_view(), name='logout'),
    path('login/', views.login_view, name='login'),
    path('register/', views.registration, name='registration'),
    path('password-change/', views.CustomPasswordChangeView.as_view(template_name='users/password_change.html', success_url='/account/', form_class=CustomPasswordChangeForm), name='password_change'),
    path('update-profile-info/', views.update_profile, name="update_profile"),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('email-change/', views.email_change, name='email_change'),
    path('tickets/', views.my_tickets, name='tickets'),
    path('update-recipient/', views.update_recipient, name="update_recipient"),
    path('add-recipient/', views.add_recipient, name="add_recipient"),
    path('delete-recipient/', views.delete_recipient, name='delete_recipient'),
]

templates/personal_cabinet_nav_pannel.html
<!-- Боковая панель -->
<div class="col-md-3 mb-4">
    <div class="list-group shadow-sm">

        <a href="{% url 'user:dashboard' %}" class="list-group-item list-group-item-action active static">
            <i class="bi bi-person-circle me-2"></i> Профіль
        </a>

        <a href="{% url 'user:my_orders' %}" class="list-group-item list-group-item-action">
            <i class="bi bi-card-checklist me-2"></i> Мої замовлення
        </a>

        <a href="{% url 'user:favorites' %}" class="list-group-item list-group-item-action">
            <i class="bi bi-heart me-2"></i> Обране
        </a>

        <a href="{% url 'user:tickets' %}" class="list-group-item list-group-item-action">
            <i class="bi bi-ticket-perforated me-2"></i> Мої звернення
        </a>

        <a href="{% url 'user:messages' %}" class="list-group-item list-group-item-action">
            <span class="position-relative">{% if user.unread_messages > 0 %}<span class="position-absolute start-0 translate-middle badge rounded-custom bg-orange" style="top: 15%;">{{ user.unread_messages }}<span class="visually-hidden">непрочитані повідомлення</span></span>{% endif %}<i class="bi bi-chat-dots me-2"></i> Повідомлення</span>
        </a>

        <a href="{% url 'user:password_change' %}" class="list-group-item list-group-item-action">
            <i class="bi bi-lock me-2"></i> Змінити пароль
        </a>

        <a href="{% url 'user:email_change' %}" class="list-group-item list-group-item-action">
            <i class="bi bi-envelope me-2"></i> Зміна пошти
        </a>

        <form method="post" action="{% url 'user:logout' %}">
        {% csrf_token %}
        <button type="submit" class="list-group-item list-group-item-action text-danger" style="border-radius: 0;">
            <i class="bi bi-box-arrow-right me-2"></i> Вийти
        </button>
        </form>

    </div>
</div>